version : '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 111111
    ports:
      - "127.0.0.1:13306:3306"
    volumes:
      - redguide_data:/var/lib/mysql
  redguide:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    volumes:
      - .:/redguide-rails
    ports:
      - "3000:3000"
    links:
      - db
volumes:
  redguide_data:
